require('dotenv').config();
const { sequelize, Book } = require('./src/models');

const books = [
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Classic',
    description: 'A novel set in the Roaring Twenties that explores themes of wealth, class, love, and the American Dream through the eyes of narrator Nick Carraway.',
    coverImage: 'https://covers.openlibrary.org/b/id/8225261-L.jpg',
    rating: 4.2,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 1925,
    pages: 180,
    isbn: '9780743273565',
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Classic',
    description: 'A timeless classic that deals with racial injustice, moral growth, and human dignity in the American South during the 1930s.',
    coverImage: 'https://covers.openlibrary.org/b/id/8810494-L.jpg',
    rating: 4.8,
    availableCopies: 2,
    totalCopies: 2,
    publishedYear: 1960,
    pages: 281,
    isbn: '9780061935466',
  },
  {
    title: '1984',
    author: 'George Orwell',
    genre: 'Dystopian',
    description: 'A chilling dystopian novel where a totalitarian government controls every aspect of life. Winston Smith struggles against a nightmarish society of surveillance and thought control.',
    coverImage: 'https://covers.openlibrary.org/b/id/8575708-L.jpg',
    rating: 4.7,
    availableCopies: 4,
    totalCopies: 4,
    publishedYear: 1949,
    pages: 328,
    isbn: '9780451524935',
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    genre: 'Dystopian',
    description: 'A futuristic society where people are genetically engineered and conditioned to be happy, raising questions about freedom, identity, and the cost of stability.',
    coverImage: 'https://covers.openlibrary.org/b/id/8406786-L.jpg',
    rating: 4.1,
    availableCopies: 2,
    totalCopies: 2,
    publishedYear: 1932,
    pages: 311,
    isbn: '9780060850524',
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'Science Fiction',
    description: 'An epic tale set on the desert planet Arrakis — the only source of the most precious substance in the universe — weaving together politics, religion, ecology, and human evolution.',
    coverImage: 'https://covers.openlibrary.org/b/id/10521270-L.jpg',
    rating: 4.8,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 1965,
    pages: 412,
    isbn: '9780441013593',
  },
  {
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    author: 'Douglas Adams',
    genre: 'Science Fiction',
    description: 'The comic science fiction journey of Arthur Dent, who travels the universe after Earth is demolished to make way for a hyperspace expressway.',
    coverImage: 'https://covers.openlibrary.org/b/id/8476099-L.jpg',
    rating: 4.6,
    availableCopies: 5,
    totalCopies: 5,
    publishedYear: 1979,
    pages: 224,
    isbn: '9780345391803',
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    genre: 'Fiction',
    description: 'A philosophical novel about a young Andalusian shepherd who dreams of finding treasure near the Egyptian pyramids, a journey that becomes a spiritual quest for self-discovery.',
    coverImage: 'https://covers.openlibrary.org/b/id/12003190-L.jpg',
    rating: 4.3,
    availableCopies: 4,
    totalCopies: 4,
    publishedYear: 1988,
    pages: 208,
    isbn: '9780062315007',
  },
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    description: 'The tale of Kvothe, a legend among men, told in his own words — from his humble origins among a troupe of traveling players to his days as a near-mythical figure.',
    coverImage: 'https://covers.openlibrary.org/b/id/8370015-L.jpg',
    rating: 4.7,
    availableCopies: 2,
    totalCopies: 2,
    publishedYear: 2007,
    pages: 662,
    isbn: '9780756404741',
  },
  {
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    description: 'The magical story of Harry Potter who discovers on his 11th birthday that he is the orphaned son of two powerful wizards and has his own magical powers.',
    coverImage: 'https://covers.openlibrary.org/b/id/10110415-L.jpg',
    rating: 4.9,
    availableCopies: 5,
    totalCopies: 5,
    publishedYear: 1997,
    pages: 223,
    isbn: '9780590353427',
  },
  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    description: 'The epic high-fantasy masterpiece following hobbit Frodo Baggins and the Fellowship on their quest to destroy the One Ring and defeat the dark lord Sauron.',
    coverImage: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    rating: 4.9,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 1954,
    pages: 1178,
    isbn: '9780618640157',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    genre: 'Non-Fiction',
    description: 'Nobel laureate Daniel Kahneman explores the two systems that drive how we think — the fast, intuitive and emotional System 1 and the slower, more deliberative System 2.',
    coverImage: 'https://covers.openlibrary.org/b/id/8691233-L.jpg',
    rating: 4.5,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 2011,
    pages: 499,
    isbn: '9780374533557',
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    genre: 'Self-Help',
    description: 'A revolutionary guide to building good habits and breaking bad ones through proven strategies based on psychology and neuroscience.',
    coverImage: 'https://covers.openlibrary.org/b/id/12647485-L.jpg',
    rating: 4.8,
    availableCopies: 6,
    totalCopies: 6,
    publishedYear: 2018,
    pages: 320,
    isbn: '9780735211292',
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    genre: 'History',
    description: 'A sweeping history of humankind from the Stone Age through the 21st century, exploring how biology and history have defined us.',
    coverImage: 'https://covers.openlibrary.org/b/id/8739161-L.jpg',
    rating: 4.6,
    availableCopies: 4,
    totalCopies: 4,
    publishedYear: 2011,
    pages: 443,
    isbn: '9780062316097',
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    genre: 'Finance',
    description: '19 short stories exploring how people think about money, and teachings about the strange ways people think about money and how to make better financial decisions.',
    coverImage: 'https://covers.openlibrary.org/b/id/12907133-L.jpg',
    rating: 4.7,
    availableCopies: 5,
    totalCopies: 5,
    publishedYear: 2020,
    pages: 256,
    isbn: '9780857197689',
  },
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    genre: 'Technology',
    description: 'A handbook of agile software craftsmanship that teaches how to write clean, readable, and maintainable code through principles and best practices.',
    coverImage: 'https://covers.openlibrary.org/b/id/8380700-L.jpg',
    rating: 4.4,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 2008,
    pages: 431,
    isbn: '9780132350884',
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt & David Thomas',
    genre: 'Technology',
    description: 'A timeless guide that examines the core process of software development from the perspective of the programmer, covering topics from personal responsibility to career development.',
    coverImage: 'https://covers.openlibrary.org/b/id/9277536-L.jpg',
    rating: 4.5,
    availableCopies: 2,
    totalCopies: 2,
    publishedYear: 1999,
    pages: 352,
    isbn: '9780135957059',
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Classic',
    description: 'The witty and romantic novel following the Bennet family, focusing on the relationship between the spirited Elizabeth Bennet and the proud Mr. Darcy.',
    coverImage: 'https://covers.openlibrary.org/b/id/8739420-L.jpg',
    rating: 4.6,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 1813,
    pages: 432,
    isbn: '9780141439518',
  },
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    genre: 'Fiction',
    description: 'Between life and death is a library containing all the lives you could have lived. Nora Seed discovers what it truly means to live, what is lost, and what might have been.',
    coverImage: 'https://covers.openlibrary.org/b/id/12471792-L.jpg',
    rating: 4.4,
    availableCopies: 4,
    totalCopies: 4,
    publishedYear: 2020,
    pages: 288,
    isbn: '9780525559474',
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    genre: 'Thriller',
    description: 'A famous painter shoots her husband five times and then never speaks another word. Her therapist becomes obsessed with uncovering the motive behind her strange silence.',
    coverImage: 'https://covers.openlibrary.org/b/id/9178376-L.jpg',
    rating: 4.3,
    availableCopies: 4,
    totalCopies: 4,
    publishedYear: 2019,
    pages: 325,
    isbn: '9781250301697',
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    genre: 'Thriller',
    description: 'A journalist and a hacker investigate a forty-year-old disappearance of a wealthy patriarch\'s niece, uncovering a dark labyrinth of family secrets.',
    coverImage: 'https://covers.openlibrary.org/b/id/8383734-L.jpg',
    rating: 4.5,
    availableCopies: 3,
    totalCopies: 3,
    publishedYear: 2005,
    pages: 672,
    isbn: '9780307454546',
  },
];

const seed = async () => {
  try {
    await sequelize.authenticate();
    console.log('✅ Connected to database');
    await sequelize.sync({ alter: true });
    console.log('✅ Database synced');

    const existingCount = await Book.count();
    if (existingCount > 0) {
      console.log(`ℹ️  Database already has ${existingCount} books. Skipping seed.`);
      console.log('   Run with --force flag to re-seed: node seedData.js --force');
      if (!process.argv.includes('--force')) {
        await sequelize.close();
        return;
      }
      await Book.destroy({ where: {} });
      console.log('🗑️  Cleared existing books');
    }

    await Book.bulkCreate(books);
    console.log(`✅ Successfully seeded ${books.length} books!`);
  } catch (err) {
    console.error('❌ Seeding failed:', err.message);
    console.error(err);
  } finally {
    await sequelize.close();
  }
};

seed();
